const cardData = [
    {
        website: "www.juancode.dev",
        instagram: "juanshocl",
        twitter: "juancodedev",
        github: "juancodedev",
        email: "cl.jmunoz@gmail.com",
        telefono: "+569983077786",
        whatsapp: "+56998307778",
        linkedin: "juancodedev",
        facebook: "juancodedev",
        nombre: "Juan Code",
        apellido: "Munoz",
        titulo: "Frontend Developer",
        descripcion: "Desarrollador frontend con más de 5 años de experiencia en React y Next.js, conocimientos en JavaScript, TypeScript, Styled Components, GraphQL y Apollo Client.",
        img: "juancode.jpg",
        imgPortada: "juancodeportada.jpg",
        created_at: "",
        updated_at: "",
        deleted_at: ""
    },
    {
        website: "www.marianadev.dev",
        instagram: "marianatech",
        twitter: "marianadev",
        github: "marianadev",
        email: "mariana.tech@gmail.com",
        telefono: "+56987654321",
        whatsapp: "+56987654321",
        linkedin: "marianadev",
        facebook: "marianadev",
        nombre: "Mariana",
        apellido: "Gomez",
        titulo: "Full Stack Developer",
        descripcion: "Full Stack Developer con experiencia en desarrollo de aplicaciones web utilizando Node.js, Express, MongoDB y React.",
        img: "marianagomez.jpg",
        imgPortada: "marianaportada.jpg",
        created_at: "",
        updated_at: "",
        deleted_at: ""
    },
    {
        website: "www.pablodev.dev",
        instagram: "pablo.code",
        twitter: "pablodev",
        github: "pablodev",
        email: "pablo.dev@gmail.com",
        telefono: "+56999887766",
        whatsapp: "+56999887766",
        linkedin: "pablodev",
        facebook: "pablodev",
        nombre: "Pablo",
        apellido: "Ramirez",
        titulo: "Backend Developer",
        descripcion: "Especialista en desarrollo backend con más de 7 años de experiencia en Node.js, Python y bases de datos relacionales y no relacionales.",
        img: "pabloramirez.jpg",
        imgPortada: "pabloportada.jpg",
        created_at: "",
        updated_at: "",
        deleted_at: ""
    },
    {
        website: "www.carlacodes.dev",
        instagram: "carla.codes",
        twitter: "carlacodes",
        github: "carlacodes",
        email: "carla.codes@gmail.com",
        telefono: "+56911223344",
        whatsapp: "+56911223344",
        linkedin: "carlacodes",
        facebook: "carlacodes",
        nombre: "Carla",
        apellido: "Torres",
        titulo: "UI/UX Designer",
        descripcion: "Diseñadora UI/UX con enfoque en la creación de interfaces intuitivas y centradas en el usuario, con experiencia en Figma, Sketch y Adobe XD.",
        img: "carlatorres.jpg",
        imgPortada: "carlaportada.jpg",
        created_at: "",
        updated_at: "",
        deleted_at: ""
    },
    {
        website: "www.alejandrodev.dev",
        instagram: "alejandro_dev",
        twitter: "alejandrodev",
        github: "alejandrodev",
        email: "alejandro.dev@gmail.com",
        telefono: "+56955667788",
        whatsapp: "+56955667788",
        linkedin: "alejandrodev",
        facebook: "alejandrodev",
        nombre: "Alejandro",
        apellido: "Perez",
        titulo: "Mobile Developer",
        descripcion: "Desarrollador de aplicaciones móviles con experiencia en React Native, Swift y Kotlin. Proyectos exitosos en iOS y Android.",
        img: "alejandroperez.jpg",
        imgPortada: "alejandroportada.jpg",
        created_at: "",
        updated_at: "",
        deleted_at: ""
    },
    {
        website: "www.fernandocodes.dev",
        instagram: "fernando.codes",
        twitter: "fernandocodes",
        github: "fernandocodes",
        email: "fernando.codes@gmail.com",
        telefono: "+56933445566",
        whatsapp: "+56933445566",
        linkedin: "fernandocodes",
        facebook: "fernandocodes",
        nombre: "Fernando",
        apellido: "López",
        titulo: "DevOps Engineer",
        descripcion: "Ingeniero DevOps con experiencia en automatización de infraestructuras utilizando Docker, Kubernetes, AWS y Azure.",
        img: "fernandolopez.jpg",
        imgPortada: "fernandoportada.jpg",
        created_at: "",
        updated_at: "",
        deleted_at: ""
    },
    {
        website: "www.sophiadev.dev",
        instagram: "sophia.codes",
        twitter: "sophiadev",
        github: "sophiadev",
        email: "sophia.dev@gmail.com",
        telefono: "+56922334455",
        whatsapp: "+56922334455",
        linkedin: "sophiadev",
        facebook: "sophiadev",
        nombre: "Sophia",
        apellido: "Martinez",
        titulo: "Data Scientist",
        descripcion: "Científica de datos con experiencia en Python, R, y análisis de grandes volúmenes de datos utilizando técnicas de Machine Learning.",
        img: "sophiamartinez.jpg",
        imgPortada: "sophiaportada.jpg",
        created_at: "",
        updated_at: "",
        deleted_at: ""
    },
    {
        website: "www.luiscodes.dev",
        instagram: "luis.codes",
        twitter: "luiscodes",
        github: "luiscodes",
        email: "luis.codes@gmail.com",
        telefono: "+56944332211",
        whatsapp: "+56944332211",
        linkedin: "luiscodes",
        facebook: "luiscodes",
        nombre: "Luis",
        apellido: "Gutierrez",
        titulo: "Cloud Engineer",
        descripcion: "Ingeniero de nube certificado con experiencia en AWS, Google Cloud y Microsoft Azure. Especialista en arquitecturas escalables y seguras.",
        img: "luisgutierrez.jpg",
        imgPortada: "luisportada.jpg",
        created_at: "",
        updated_at: "",
        deleted_at: ""
    },
    {
        website: "www.anafrontend.dev",
        instagram: "ana.frontend",
        twitter: "anafrontend",
        github: "anafrontend",
        email: "ana.frontend@gmail.com",
        telefono: "+56999882233",
        whatsapp: "+56999882233",
        linkedin: "anafrontend",
        facebook: "anafrontend",
        nombre: "Ana",
        apellido: "Rodriguez",
        titulo: "Frontend Developer",
        descripcion: "Desarrolladora frontend con enfoque en optimización de rendimiento y accesibilidad en aplicaciones web modernas.",
        img: "anarodriguez.jpg",
        imgPortada: "anaportada.jpg",
        created_at: "",
        updated_at: "",
        deleted_at: ""
    },
    {
        website: "www.diego.codes.dev",
        instagram: "diego.codes",
        twitter: "diegocodes",
        github: "diegocodes",
        email: "diego.codes@gmail.com",
        telefono: "+56977889900",
        whatsapp: "+56977889900",
        linkedin: "diegocodes",
        facebook: "diegocodes",
        nombre: "Diego",
        apellido: "Mendoza",
        titulo: "Security Specialist",
        descripcion: "Especialista en seguridad informática con experiencia en pentesting, auditoría de sistemas y análisis de vulnerabilidades.",
        img: "diegomendoza.jpg",
        imgPortada: "diegoportada.jpg",
        created_at: "",
        updated_at: "",
        deleted_at: ""
    },
    
]
export default cardData