import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Next bussines card.",
  description: "Generated by juancode.dev",
};

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="es">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

import { Analytics } from "@vercel/analytics/react"
import localFont from 'next/font/local'
import { cn } from '@/app/lib/utils'
import './globals.css'

const fontHeading = localFont({
  src: './fonts/GeistVF.woff',
  display: 'swap',
  variable: '--font-heading',
})

const fontBody = localFont({
  src: './fonts/GeistMonoVF.woff',
  display: 'swap',
  variable: '--font-body',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Analytics/>
      <body 
        className={cn(
          'antialiased',
          fontHeading.variable,
          fontBody.variable
        )}
      >
        {children}
      </body>
    </html>
  )
}